version = 0.1

[default.deploy.parameters]
stack_name = "freshguard-dev"
resolve_s3 = true
s3_prefix = "freshguard-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\" AllowedWebOrigins=\"http://localhost:3000\""
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
